name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Part 1 PDF
        run: |
          test -f "PROG PART 1 (1).pdf"

      - name: Validation successful
        run: echo "RaceDay Part 1 PDF is present."
